const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='sevenlab02', OLD='sevenlab01';
const roleName={P:'Portiere',D:'Difensore',C:'Centrocampista',A:'Attaccante'};
const formations={7:{'1-3-2-1':[['P','P',8,50],['D1','D',28,20],['D2','D',28,50],['D3','D',28,80],['C1','C',56,35],['C2','C',56,65],['A','A',82,50]],'1-3-3':[['P','P',8,50],['D1','D',28,20],['D2','D',28,50],['D3','D',28,80],['A1','A',70,20],['A2','A',70,50],['A3','A',70,80]],'1-2-3-1':[['P','P',8,50],['D1','D',29,34],['D2','D',29,66],['C1','C',56,18],['C2','C',56,50],['C3','C',56,82],['A','A',82,50]],'1-2-2-2':[['P','P',8,50],['D1','D',28,35],['D2','D',28,65],['C1','C',54,34],['C2','C',54,66],['A1','A',80,35],['A2','A',80,65]]},5:{'2-2+J':[['DC1','D/C',27,30],['DC2','D/C',27,70],['J','C',50,50],['AC1','A/C',73,30],['AC2','A/C',73,70]]},4:{'2-2':[['DC1','D/C',30,30],['DC2','D/C',30,70],['AC1','A/C',70,30],['AC2','A/C',70,70]]},3:{'1-2':[['DC','D/C',30,50],['AC1','A/C',70,32],['AC2','A/C',70,68]]}};
const stats=[['shot','🎯','Tiro'],['goal','⚽','Gol'],['assist','🅰️','Assist'],['save','🧤','Parata'],['passok','✓','Pass +'],['passbad','✕','Pass -'],['lost','❌','Persa'],['recover','🔄','Recupero']];
function emptyCurrent(){return {id:null,dateISO:null,dateLabel:'',title:'',present:[],size:7,module:'1-2-3-1',teams:{A:{},B:{}},events:[],phase:'ready',elapsed:0,startedAt:null,score:{A:0,B:0},outRoles:[],segments:[],activeSegment:null};}
function fresh(){return {roster:[],history:[],current:emptyCurrent()};}
function load(){let x=JSON.parse(localStorage.getItem(KEY)||'null');if(x){x.current=Object.assign(emptyCurrent(),x.current||{});x.history=x.history||[];x.roster=x.roster||[];return x;}let old=JSON.parse(localStorage.getItem(OLD)||'null');let n=fresh();if(old?.roster)n.roster=old.roster;return n;}
let DB=load(),pick=null,tick=null;
function save(){localStorage.setItem(KEY,JSON.stringify(DB));}
function current(){return DB.current;}
function nowDate(){let d=new Date();return {iso:d.toISOString(),label:d.toLocaleDateString('it-IT',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})};}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),900);}
function go(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));if(id==='formazioni')renderForm();if(id==='live')renderLive();if(id==='storico')renderHistory();scrollTo(0,0);}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.remove('show'));
$('#addBtn').onclick=()=>{let n=$('#newName').value.trim(),r=$('#newRole').value;if(!n)return toast('Inserisci un nome');DB.roster.push({id:String(Date.now()+Math.random()),name:n,role:r});$('#newName').value='';save();renderRoster();renderPresence();toast('Giocatore aggiunto');};
function renderRoster(){let e=$('#rosterList');if(!DB.roster.length){e.innerHTML='<div class="empty">Aggiungi il primo giocatore.</div>';return;}e.innerHTML=DB.roster.map(p=>`<div class="player"><div class="avatar">${esc(p.name[0]||'?').toUpperCase()}</div><div class="grow"><div class="name">${esc(p.name)}</div><div class="meta">${roleName[p.role]}</div></div><span class="role">${p.role}</span><button class="btn small danger" data-del="${p.id}">×</button></div>`).join('');$$('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Rimuovere questo giocatore dalla rosa?')){DB.roster=DB.roster.filter(p=>p.id!==b.dataset.del);save();renderRoster();renderPresence();}});}
function renderPresence(){let d=nowDate();$('#todayLabel').textContent='Data automatica: '+d.label;let e=$('#presenceList');if(!DB.roster.length){e.innerHTML='<div class="empty">Prima inserisci la rosa.</div>';return;}let selected=current().present||[];e.innerHTML=DB.roster.map(p=>`<label><input type="checkbox" value="${p.id}" ${selected.includes(p.id)?'checked':''}><span>${esc(p.name)}<small class="meta" style="display:block">${p.role}</small></span></label>`).join('');}
$('#presenceBtn').onclick=()=>{let d=nowDate(),ids=$$('#presenceList input:checked').map(x=>x.value);if(ids.length<6&&!confirm(`Hai selezionato solo ${ids.length} presenti. Continuare?`))return;DB.current=emptyCurrent();let c=current();c.id='s'+Date.now();c.dateISO=d.iso;c.dateLabel=d.label;c.title=$('#trainingTitle').value.trim()||'Allenamento';c.present=ids;save();renderForm();go('formazioni');};
function renderForm(){let c=current(),mods=Object.keys(formations[c.size]);if(!mods.includes(c.module))c.module=mods[0];$('#sizeSeg').innerHTML=[3,4,5,7].map(n=>`<button class="seg ${c.size===n?'on':''}" data-size="${n}">${n} vs ${n}</button>`).join('');$('#moduleSeg').innerHTML=mods.map(m=>`<button class="seg ${c.module===m?'on':''}" data-mod="${m}">${m}</button>`).join('');$$('[data-size]').forEach(b=>b.onclick=()=>{c.size=+b.dataset.size;c.module=Object.keys(formations[c.size])[0];c.teams={A:{},B:{}};c.outRoles=[];save();renderForm();});$$('[data-mod]').forEach(b=>b.onclick=()=>{c.module=b.dataset.mod;c.teams={A:{},B:{}};c.outRoles=[];save();renderForm();});renderPitch('A');renderPitch('B');}
function renderPitch(t){let c=current(),e=$('#pitch'+t);e.innerHTML='';formations[c.size][c.module].forEach(([k,r,x,y])=>{let a=c.teams[t][k],p=DB.roster.find(z=>z.id===a?.pid),b=document.createElement('button');b.className='slot '+(!p?'empty':a.outRole?'outrole':'');b.style.left=x+'%';b.style.top=y+'%';b.innerHTML=p?`${esc(p.name)}<span class="tiny">${k}${a.outRole?' · fuori ruolo':''}</span>`:`+ ${k}<span class="tiny">${r}</span>`;b.onclick=()=>openPicker(t,k,r);e.appendChild(b);});}
function assignedIds(){let c=current();return Object.values(c.teams.A).concat(Object.values(c.teams.B)).map(x=>x?.pid).filter(Boolean);}
function compatible(r,d){if(d==='D/C')return ['D','C'].includes(r);if(d==='A/C')return ['A','C'].includes(r);return r===d;}
function openPicker(t,k,d){let c=current();pick={t,k,d};$('#pickerTitle').textContent=`Squadra ${t} · ${k} (${d})`;let avail=DB.roster.filter(p=>c.present.includes(p.id)&&(!assignedIds().includes(p.id)||c.teams[t][k]?.pid===p.id));let good=avail.filter(p=>compatible(p.role,d)),other=avail.filter(p=>!compatible(p.role,d));let block='';if(c.teams[t][k])block+='<button class="choice" data-pid="">➖ Libera posizione</button>';block+=`<div class="groupTitle">CONSIGLIATI PER RUOLO (${good.length})</div>`+(good.length?good.map(p=>choiceHtml(p,true)).join(''):'<div class="sub">Nessun giocatore di ruolo disponibile.</div>');block+=`<div class="groupTitle">ADATTABILI TRA I PRESENTI (${other.length})</div>`+(other.length?other.map(p=>choiceHtml(p,false)).join(''):'<div class="sub">Nessun altro presente disponibile.</div>');$('#pickerChoices').innerHTML=block;$$('#pickerChoices [data-pid]').forEach(b=>b.onclick=()=>assignPick(b.dataset.pid));$('#pickerModal').classList.add('show');}
function choiceHtml(p,ok){return `<button class="choice" data-pid="${p.id}"><span><b>${esc(p.name)}</b><small class="meta" style="display:block">${roleName[p.role]}</small></span><span class="tag ${ok?'':'warn'}">${ok?'di ruolo':'adattato'}</span></button>`;}
function assignPick(pid){let c=current();if(!pid){delete c.teams[pick.t][pick.k];}else{let p=DB.roster.find(x=>x.id===pid),out=!compatible(p.role,pick.d);c.teams[pick.t][pick.k]={pid,desired:pick.d,outRole:out};if(out)c.outRoles.push({pid,team:pick.t,slot:pick.k,desired:pick.d,at:0});}save();$('#pickerModal').classList.remove('show');renderForm();}
$$('[data-clear]').forEach(b=>b.onclick=()=>{current().teams[b.dataset.clear]={};save();renderForm();});
$('#toLive').onclick=()=>{let c=current(),need=c.size*2,n=new Set(assignedIds()).size;if(n<need&&!confirm(`Hai assegnato ${n} giocatori su ${need}. Continuare?`))return;go('live');};
function fieldIds(){return [...new Set(assignedIds())];}
function teamOf(id){let c=current();return Object.values(c.teams.A).some(x=>x?.pid===id)?'A':'B';}
function assignmentOf(id){let c=current();for(let t of ['A','B'])for(let k in c.teams[t])if(c.teams[t][k]?.pid===id)return {team:t,slot:k,...c.teams[t][k]};return null;}
function stat(id,t){return current().events.filter(e=>!e.void&&e.pid===id&&e.type===t).length;}
function renderLive(){let c=current();updateTimer();$('#scoreA').textContent=c.score.A;$('#scoreB').textContent=c.score.B;let ids=fieldIds();$('#livePlayers').innerHTML=ids.length?ids.map(id=>{let p=DB.roster.find(x=>x.id===id),a=assignmentOf(id);return `<div class="liveplayer"><div class="liveplayer-top"><div><div class="name">${esc(p?.name||'')}</div><div class="meta">${roleName[p?.role]||''} ${a?.outRole?'· ⚠️ fuori ruolo':''}</div></div><span class="role">Squadra ${a?.team||''}</span></div><div class="countergrid">${stats.map(([t,i,l])=>`<button class="counter" data-ev="${id}|${t}"><b>${i} ${stat(id,t)}</b><small>${l}</small></button>`).join('')}</div></div>`;}).join(''):'<div class="empty">Prima prepara le formazioni.</div>';$$('[data-ev]').forEach(b=>b.onclick=()=>addEvent(...b.dataset.ev.split('|')));renderLast();}
function elapsed(){let c=current();return c.elapsed+(c.startedAt?Math.floor((Date.now()-c.startedAt)/1000):0);}
function addEvent(pid,type){let c=current(),tm=teamOf(pid);c.events.push({id:Date.now()+Math.random(),pid,type,t:elapsed(),phase:c.phase,team:tm,void:false});if(type==='goal'&&tm)c.score[tm]++;save();renderLive();let p=DB.roster.find(x=>x.id===pid),st=stats.find(x=>x[0]===type);toast((p?.name||'')+' · '+st[2]);}
$$('[data-score]').forEach(b=>b.onclick=()=>{let t=b.dataset.score;current().score[t]++;save();renderLive();toast('Punteggio aggiornato');});
function updateTimer(){let c=current(),s=elapsed(),m=String(Math.floor(s/60)).padStart(2,'0'),q=String(s%60).padStart(2,'0');$('#timer').textContent=m+':'+q;$('#phaseLabel').textContent=c.phase==='pausa'?'INTERVALLO':String(c.phase).toUpperCase();}
function startTick(){clearInterval(tick);tick=setInterval(updateTimer,1000);}
function snapshotTeams(){let c=current(),x={A:[],B:[]};for(let t of ['A','B'])x[t]=Object.values(c.teams[t]).map(v=>v?.pid).filter(Boolean).sort();return x;}
function beginSegment(){let c=current();if(c.activeSegment)return;let s=snapshotTeams();c.activeSegment={start:elapsed(),scoreStart:{...c.score},A:s.A,B:s.B};}
function closeSegment(){let c=current();if(!c.activeSegment)return;c.segments.push({...c.activeSegment,end:elapsed(),scoreEnd:{...c.score}});c.activeSegment=null;}
$('#playBtn').onclick=()=>{let c=current();if(c.startedAt)return;if(c.phase==='ready')c.phase='1° TEMPO';else if(c.phase==='pausa')c.phase='2° TEMPO';c.startedAt=Date.now();beginSegment();save();startTick();updateTimer();};
$('#pauseBtn').onclick=()=>{let c=current();if(c.startedAt){c.elapsed=elapsed();c.startedAt=null;}closeSegment();c.phase='pausa';clearInterval(tick);save();updateTimer();};
$('#stopBtn').onclick=()=>{let c=current();if(!c.id)return toast('Nessuna sessione attiva');if(c.startedAt){c.elapsed=elapsed();c.startedAt=null;}closeSegment();c.phase='finita';clearInterval(tick);archiveSession();};
function renderLast(){let e=[...current().events].reverse().find(x=>!x.void);if(!e){$('#lastEvent').textContent='';return;}let p=DB.roster.find(x=>x.id===e.pid),st=stats.find(x=>x[0]===e.type);$('#lastEvent').textContent=`· ${p?.name||''} ${st?.[2]||''}`;}
$('#undoBtn').onclick=()=>{let c=current(),e=[...c.events].reverse().find(x=>!x.void);if(!e)return toast('Niente da annullare');e.void=true;if(e.type==='goal'&&e.team&&c.score[e.team]>0)c.score[e.team]--;save();renderLive();toast('Evento annullato');};
$('#subBtn').onclick=()=>openSub();
function openSub(){let f=fieldIds();$('#subChoices').innerHTML='<div class="sub">Chi esce?</div>'+f.map(id=>{let p=DB.roster.find(x=>x.id===id),a=assignmentOf(id);return `<button class="choice" data-out="${id}"><span><b>${esc(p?.name||'')}</b><small class="meta" style="display:block">Squadra ${a?.team} · ${a?.slot}</small></span>→</button>`;}).join('');$$('[data-out]').forEach(b=>b.onclick=()=>chooseIn(b.dataset.out));$('#subModal').classList.add('show');}
function chooseIn(out){let c=current(),bench=DB.roster.filter(p=>c.present.includes(p.id)&&!fieldIds().includes(p.id));if(!bench.length)return toast('Nessuno in panchina');let a=assignmentOf(out),desired=a?.desired||'C';let good=bench.filter(p=>compatible(p.role,desired)),other=bench.filter(p=>!compatible(p.role,desired));$('#subChoices').innerHTML=`<div class="sub">Sostituisci nella posizione <b>${a?.slot||''}</b>.</div><div class="groupTitle">DI RUOLO</div>${good.map(p=>subChoice(p,true)).join('')||'<div class="sub">Nessuno.</div>'}<div class="groupTitle">ADATTABILI</div>${other.map(p=>subChoice(p,false)).join('')||'<div class="sub">Nessuno.</div>'}`;$$('[data-in]').forEach(b=>b.onclick=()=>doSub(out,b.dataset.in));}
function subChoice(p,ok){return `<button class="choice" data-in="${p.id}"><span><b>${esc(p.name)}</b><small class="meta" style="display:block">${roleName[p.role]}</small></span><span class="tag ${ok?'':'warn'}">${ok?'di ruolo':'adattato'}</span></button>`;}
function doSub(outId,inId){let c=current(),a=assignmentOf(outId);if(!a)return;closeSegment();let p=DB.roster.find(x=>x.id===inId),outRole=!compatible(p.role,a.desired);c.teams[a.team][a.slot]={pid:inId,desired:a.desired,outRole};if(outRole)c.outRoles.push({pid:inId,team:a.team,slot:a.slot,desired:a.desired,at:elapsed()});c.events.push({id:Date.now()+Math.random(),pid:inId,type:'sub',outId,team:a.team,t:elapsed(),void:false});if(c.startedAt)beginSegment();save();$('#subModal').classList.remove('show');renderLive();toast('Cambio registrato');}
function archiveSession(){let c=current(),copy=JSON.parse(JSON.stringify(c));copy.savedAt=new Date().toISOString();DB.history.unshift(copy);DB.current=emptyCurrent();save();renderHistory();go('storico');toast(`Sessione salvata · ${copy.score.A}-${copy.score.B}`);}
function renderHistory(){let e=$('#historyList');if(!DB.history.length)e.innerHTML='<div class="empty">Nessuna sessione registrata.</div>';else e.innerHTML=DB.history.map(s=>`<div class="historyItem"><div class="grow"><div class="name">${esc(s.title)} · ${s.score.A}-${s.score.B}</div><div class="meta">${esc(s.dateLabel)} · ${Math.floor((s.elapsed||0)/60)} min · ${s.present.length} presenti</div></div><button class="btn small ghost" data-open="${s.id}">Apri</button><button class="btn small danger" data-delete="${s.id}">Elimina</button></div>`).join('');$$('[data-open]').forEach(b=>b.onclick=()=>openSession(b.dataset.open));$$('[data-delete]').forEach(b=>b.onclick=()=>deleteSession(b.dataset.delete));renderCombos();}
function deleteSession(id){let s=DB.history.find(x=>x.id===id);if(!s)return;if(confirm(`Eliminare definitivamente la sessione del ${s.dateLabel}?`)){DB.history=DB.history.filter(x=>x.id!==id);save();renderHistory();toast('Sessione eliminata');}}
function openSession(id){let s=DB.history.find(x=>x.id===id);if(!s)return;$('#sessionDetail').innerHTML=sessionReport(s);$('#sessionModal').classList.add('show');}
function sessionReport(s){let valid=s.events.filter(e=>!e.void&&e.type!=='sub'),ids=[...new Set(valid.map(e=>e.pid))],outs=uniqueOutRoles(s);let rows=ids.map(id=>{let p=DB.roster.find(x=>x.id===id);return `<tr><td>${esc(p?.name||'')}</td>${['goal','shot','assist','passok','passbad','lost','recover','save'].map(t=>`<td>${valid.filter(e=>e.pid===id&&e.type===t).length}</td>`).join('')}</tr>`;}).join('');let outHtml=outs.length?`<div class="groupTitle">FUORI RUOLO</div>${outs.map(o=>`<div class="combo">⚠️ <b>${esc(playerName(o.pid))}</b><span class="meta">adattato come ${esc(o.desired)} · Squadra ${o.team}</span></div>`).join('')}`:'<div class="sub">Nessun giocatore utilizzato fuori ruolo.</div>';return `<div class="kpis"><div class="kpi"><b>${s.score.A}-${s.score.B}</b><small>Risultato</small></div><div class="kpi"><b>${Math.floor((s.elapsed||0)/60)}'</b><small>Durata</small></div><div class="kpi"><b>${s.present.length}</b><small>Presenti</small></div></div><div class="sub">${esc(s.dateLabel)} · ${esc(s.title)} · ${s.size}v${s.size} · ${esc(s.module)}</div><div style="overflow:auto"><table class="report"><thead><tr><th>Giocatore</th><th>G</th><th>T</th><th>A</th><th>P+</th><th>P-</th><th>Pers.</th><th>Rec.</th><th>Par.</th></tr></thead><tbody>${rows}</tbody></table></div>${outHtml}`;}
function uniqueOutRoles(s){let seen=new Set();return (s.outRoles||[]).filter(o=>{let k=o.pid+'|'+o.desired+'|'+o.team;if(seen.has(k))return false;seen.add(k);return true;});}
function renderCombos(){let box=$('#comboAnalysis'),segments=DB.history.flatMap(s=>(s.segments||[]).map(g=>({...g,sessionId:s.id}))).filter(g=>(g.end-g.start)>0);if(!segments.length){box.innerHTML='<div class="empty">Servono sessioni con Play/Stop per calcolare le combinazioni.</div>';return;}let lineups=new Map(),pairs=new Map();for(let g of segments){let mins=(g.end-g.start)/60;for(let team of ['A','B']){let opp=team==='A'?'B':'A',gf=g.scoreEnd[team]-g.scoreStart[team],ga=g.scoreEnd[opp]-g.scoreStart[opp],diff=gf-ga,ids=g[team]||[],lk=ids.slice().sort().join('|');acc(lineups,lk,{ids,mins,gf,ga,diff,segments:1});for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){let ps=[ids[i],ids[j]].sort(),pk=ps.join('|');acc(pairs,pk,{ids:ps,mins,gf,ga,diff,segments:1});}}}let L=[...lineups.values()].sort(rank).slice(0,5),P=[...pairs.values()].filter(x=>x.mins>=3).sort(rank).slice(0,8);box.innerHTML=`<div class="groupTitle">MIGLIORI FORMAZIONI / LINE-UP</div>${L.map(comboHtml).join('')||'<div class="sub">Dati insufficienti.</div>'}<div class="groupTitle">MIGLIORI COPPIE</div>${P.map(comboHtml).join('')||'<div class="sub">Dati insufficienti.</div>'}<div class="sub mt">Il ranking usa differenziale gol e minuti giocati insieme. Più sessioni registri, più il dato diventa utile.</div>`;}
function acc(map,k,v){if(!map.has(k))map.set(k,{ids:v.ids,mins:0,gf:0,ga:0,diff:0,segments:0});let x=map.get(k);x.mins+=v.mins;x.gf+=v.gf;x.ga+=v.ga;x.diff+=v.diff;x.segments+=v.segments;}
function rank(a,b){let ra=a.diff/Math.max(a.mins,1),rb=b.diff/Math.max(b.mins,1);return rb-ra||b.mins-a.mins;}
function comboHtml(x){let rate=x.diff/Math.max(x.mins,1),cls=x.diff>=0?'positive':'negative';return `<div class="combo"><b>${x.ids.map(playerName).map(esc).join(' + ')}</b><span class="meta">${x.mins.toFixed(1)} min · GF ${x.gf} / GS ${x.ga} · <span class="${cls}">${x.diff>=0?'+':''}${x.diff}</span> · diff/min ${rate.toFixed(2)}</span></div>`;}
function playerName(id){return DB.roster.find(p=>p.id===id)?.name||'Giocatore';}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
renderRoster();renderPresence();renderForm();renderLive();renderHistory();if(current().startedAt)startTick();save();