const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const K='sevenlab04',PREV=['sevenlab03','sevenlab02','sevenlab01'],SHOT_WINDOW=8;
const RN={P:'Portiere',D:'Difensore',C:'Centrocampista',A:'Attaccante'};
const F={
7:{'1-3-2-1':[['P','P',8,50],['D1','D',28,20],['D2','D',28,50],['D3','D',28,80],['C1','C',56,35],['C2','C',56,65],['A','A',82,50]],'1-3-3':[['P','P',8,50],['D1','D',28,20],['D2','D',28,50],['D3','D',28,80],['A1','A',70,20],['A2','A',70,50],['A3','A',70,80]],'1-2-3-1':[['P','P',8,50],['D1','D',29,34],['D2','D',29,66],['C1','C',56,18],['C2','C',56,50],['C3','C',56,82],['A','A',82,50]],'1-2-2-2':[['P','P',8,50],['D1','D',28,35],['D2','D',28,65],['C1','C',54,34],['C2','C',54,66],['A1','A',80,35],['A2','A',80,65]]},
6:{'1-2-1-2':[['P','P',8,50],['D1','D',29,34],['D2','D',29,66],['C','C',55,50],['A1','A',80,34],['A2','A',80,66]]},
5:{'2-2+J':[['DC1','D/C',27,30],['DC2','D/C',27,70],['J','C',50,50],['AC1','A/C',73,30],['AC2','A/C',73,70]]},
4:{'2-2':[['DC1','D/C',30,30],['DC2','D/C',30,70],['AC1','A/C',70,30],['AC2','A/C',70,70]]},
3:{'1-2':[['DC','D/C',30,50],['AC1','A/C',70,32],['AC2','A/C',70,68]]}
};
const FS=[['shot','🎯','Tiro'],['goal','⚽','Gol'],['assist','🅰️','Assist'],['passok','✓','Pass +'],['passbad','✕','Pass -'],['lost','❌','Persa'],['recover','🔄','Recupero']];
const KS=[['save','🧤','Parata'],['passok','✓','Pass +'],['passbad','✕','Pass -']];
const BASE={goal:5,assist:3,shot_on:1,shot_off:0,recover:1.5,lost:-1.5,passok:.2,passbad:-.5,save:2};
const MULT={
P:{save:1.35,passok:1.15,passbad:1.20},
D:{goal:1,assist:1,shot_on:1,shot_off:1,recover:1.30,lost:1.20,passok:1.15,passbad:1.15},
C:{goal:1.05,assist:1.20,shot_on:1.05,shot_off:1,recover:1.15,lost:1.10,passok:1.25,passbad:1.10},
A:{goal:1.25,assist:1.10,shot_on:1.15,shot_off:1,recover:1,lost:1,passok:1,passbad:1}
};
function EC(){return{id:null,dateISO:null,dateLabel:'',title:'',present:[],size:7,module:'1-2-3-1',teams:{A:{},B:{}},events:[],phase:'ready',elapsed:0,startedAt:null,score:{A:0,B:0},outRoles:[],segments:[],activeSegment:null}}
function load(){let d=JSON.parse(localStorage.getItem(K)||'null');if(!d){for(const k of PREV){d=JSON.parse(localStorage.getItem(k)||'null');if(d)break}}d=d||{roster:[],history:[],current:EC()};d.current=Object.assign(EC(),d.current||{});d.roster=d.roster||[];d.history=d.history||[];return d}
let DB=load(),pick,tick;
function save(){localStorage.setItem(K,JSON.stringify(DB))}function C(){return DB.current}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(x){let e=$('#toast');e.textContent=x;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),950)}
function nd(){let d=new Date;return{iso:d.toISOString(),label:d.toLocaleDateString('it-IT',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})}}
function go(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));if(id==='formazioni')renderForm();if(id==='live')renderLive();if(id==='storico')renderHistory();scrollTo(0,0)}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.remove('show'));
$('#addBtn').onclick=()=>{let n=$('#newName').value.trim(),r=$('#newRole').value;if(!n)return toast('Inserisci un nome');DB.roster.push({id:''+Date.now()+Math.random(),name:n,role:r});$('#newName').value='';save();renderRoster();renderPresence()};
function renderRoster(){let e=$('#rosterList');e.innerHTML=DB.roster.length?DB.roster.map(p=>`<div class="player"><div class="avatar">${esc((p.name[0]||'?').toUpperCase())}</div><div class="grow"><div class="name">${esc(p.name)}</div><div class="meta">${RN[p.role]}</div></div><span class="role">${p.role}</span><button class="btn small danger" data-del="${p.id}">×</button></div>`).join(''):'<div class="empty">Aggiungi il primo giocatore.</div>';$$('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Rimuovere questo giocatore?')){DB.roster=DB.roster.filter(p=>p.id!==b.dataset.del);save();renderRoster();renderPresence()}})}
function renderPresence(){let d=nd();$('#todayLabel').textContent='Data automatica: '+d.label;let sel=C().present||[];$('#presenceList').innerHTML=DB.roster.length?DB.roster.map(p=>`<label><input type="checkbox" value="${p.id}" ${sel.includes(p.id)?'checked':''}><span>${esc(p.name)}<small class="meta" style="display:block">${p.role}</small></span></label>`).join(''):'<div class="empty">Prima inserisci la rosa.</div>'}
$('#presenceBtn').onclick=()=>{let d=nd(),ids=$$('#presenceList input:checked').map(x=>x.value);DB.current=EC();Object.assign(C(),{id:'s'+Date.now(),dateISO:d.iso,dateLabel:d.label,title:$('#trainingTitle').value.trim()||'Allenamento',present:ids});save();go('formazioni')};
function renderForm(){let c=C(),mods=Object.keys(F[c.size]);if(!mods.includes(c.module))c.module=mods[0];$('#sizeSeg').innerHTML=[3,4,5,6,7].map(n=>`<button class="seg ${c.size===n?'on':''}" data-size="${n}">${n} vs ${n}</button>`).join('');$('#moduleSeg').innerHTML=mods.map(m=>`<button class="seg ${c.module===m?'on':''}" data-mod="${m}">${m}</button>`).join('');$$('[data-size]').forEach(b=>b.onclick=()=>{c.size=+b.dataset.size;c.module=Object.keys(F[c.size])[0];c.teams={A:{},B:{}};save();renderForm()});$$('[data-mod]').forEach(b=>b.onclick=()=>{c.module=b.dataset.mod;c.teams={A:{},B:{}};save();renderForm()});renderPitch('A');renderPitch('B')}
function renderPitch(t){let c=C(),e=$('#pitch'+t);e.innerHTML='';F[c.size][c.module].forEach(([k,r,x,y])=>{let a=c.teams[t][k],p=DB.roster.find(z=>z.id===a?.pid),b=document.createElement('button');b.className='slot '+(!p?'empty':a.outRole?'outrole':'');b.style.left=x+'%';b.style.top=y+'%';b.innerHTML=p?`${esc(p.name)}<span class="tiny">${k}${a.outRole?' · fuori ruolo':''}</span>`:`+ ${k}<span class="tiny">${r}</span>`;b.onclick=()=>openPicker(t,k,r);e.appendChild(b)})}
function assigned(){return Object.values(C().teams.A).concat(Object.values(C().teams.B)).map(x=>x?.pid).filter(Boolean)}
function compatible(r,d){return d==='D/C'?['D','C'].includes(r):d==='A/C'?['A','C'].includes(r):r===d}
function openPicker(t,k,d){pick={t,k,d};let c=C(),av=DB.roster.filter(p=>c.present.includes(p.id)&&(!assigned().includes(p.id)||c.teams[t][k]?.pid===p.id)),good=av.filter(p=>compatible(p.role,d)),other=av.filter(p=>!compatible(p.role,d));$('#pickerTitle').textContent=`Squadra ${t} · ${k} (${d})`;$('#pickerChoices').innerHTML=(c.teams[t][k]?'<button class="choice" data-pid="">➖ Libera posizione</button>':'')+`<div class="groupTitle">CONSIGLIATI (${good.length})</div>`+good.map(p=>choice(p,true)).join('')+`<div class="groupTitle">ADATTABILI (${other.length})</div>`+other.map(p=>choice(p,false)).join('');$$('#pickerChoices [data-pid]').forEach(b=>b.onclick=()=>assignPick(b.dataset.pid));$('#pickerModal').classList.add('show')}
function choice(p,ok){return`<button class="choice" data-pid="${p.id}"><span><b>${esc(p.name)}</b><small class="meta" style="display:block">${RN[p.role]}</small></span><span class="tag ${ok?'':'warn'}">${ok?'di ruolo':'adattato'}</span></button>`}
function assignPick(pid){let c=C();if(!pid)delete c.teams[pick.t][pick.k];else{let p=DB.roster.find(x=>x.id===pid),out=!compatible(p.role,pick.d);c.teams[pick.t][pick.k]={pid,desired:pick.d,outRole:out};if(out)c.outRoles.push({pid,team:pick.t,slot:pick.k,desired:pick.d,at:elapsed()})}save();$('#pickerModal').classList.remove('show');renderForm()}
$$('[data-clear]').forEach(b=>b.onclick=()=>{C().teams[b.dataset.clear]={};save();renderForm()});$('#toLive').onclick=()=>go('live');
function teamOf(id,s=C()){return Object.values(s.teams.A||{}).some(x=>x?.pid===id)?'A':Object.values(s.teams.B||{}).some(x=>x?.pid===id)?'B':null}
function assignmentOf(id){for(let t of ['A','B'])for(let k in C().teams[t])if(C().teams[t][k]?.pid===id)return{team:t,slot:k,...C().teams[t][k]};return null}
function cnt(id,t,s=C()){return(s.events||[]).filter(e=>!e.void&&e.pid===id&&e.type===t).length}
function shots(id,s=C()){return cnt(id,'shot',s)+cnt(id,'goal',s)}
function onTarget(id,s=C()){return(s.events||[]).filter(e=>!e.void&&e.pid===id&&(e.type==='goal'||(e.type==='shot'&&e.onTarget))).length}
function pstats(id,s=C()){let sh=shots(id,s),g=cnt(id,'goal',s),on=onTarget(id,s),a=cnt(id,'assist',s),po=cnt(id,'passok',s),pb=cnt(id,'passbad',s),r=cnt(id,'recover',s),l=cnt(id,'lost',s),sv=cnt(id,'save',s);return{sh,g,on,a,po,pb,r,l,sv,pp:po+pb?po/(po+pb)*100:0,cv:sh?g/sh*100:0,tp:sh?on/sh*100:0}}
function eventKey(e){if(e.type==='shot')return e.onTarget?'shot_on':'shot_off';return e.type}
function playerScore(id,s){let p=DB.roster.find(x=>x.id===id),role=p?.role||'C',parts={},total=0;(s.events||[]).filter(e=>!e.void&&e.pid===id).forEach(e=>{let k=eventKey(e),base=BASE[k]??0,m=(MULT[role]&&MULT[role][k])??1,val=base*m;parts[k]=(parts[k]||0)+val;total+=val});return{total,parts,vote:voteFromPoints(total)}}
function voteFromPoints(x){if(x<=-5)return 4;if(x<=-1)return 4.5;if(x<=3)return 5;if(x<=6)return 5.5;if(x<=10)return 6;if(x<=14)return 6.5;if(x<=19)return 7;if(x<=24)return 7.5;if(x<=30)return 8;if(x<=37)return 8.5;if(x<=45)return 9;if(x<=55)return 9.5;return 10}
function renderLive(){let c=C();updateTimer();$('#scoreA').textContent=c.score.A;$('#scoreB').textContent=c.score.B;let ids=[...new Set(assigned())];$('#livePlayers').innerHTML=ids.map(id=>{let p=DB.roster.find(x=>x.id===id),a=assignmentOf(id),set=p?.role==='P'?KS:FS,z=pstats(id,c),sc=playerScore(id,c);return`<div class="liveplayer"><div class="liveplayer-top"><div><div class="name">${esc(p?.name||'')}</div><div class="meta">${RN[p?.role]||''} ${a?.outRole?'· ⚠️ fuori ruolo':''}</div></div><span class="role">Squadra ${a?.team||''}</span></div><div class="countergrid ${p?.role==='P'?'keepergrid':''}">${set.map(([t,i,l])=>`<button class="counter" data-ev="${id}|${t}"><b>${i} ${t==='shot'?z.sh:cnt(id,t)}</b><small>${l}</small></button>`).join('')}</div><div class="microstats">Punti ${sc.total.toFixed(1)} · Voto ${sc.vote.toFixed(1)}${p?.role!=='P'?` · Tiri ${z.sh} · Porta ${z.on} · Precisione ${z.tp.toFixed(0)}% · Conversione ${z.cv.toFixed(0)}%`:''}</div></div>`}).join('')||'<div class="empty">Prima prepara le formazioni.</div>';$$('[data-ev]').forEach(b=>b.onclick=()=>addEvent(...b.dataset.ev.split('|')));renderLast()}
function elapsed(){let c=C();return c.elapsed+(c.startedAt?Math.floor((Date.now()-c.startedAt)/1000):0)}
function addEvent(pid,type){let c=C(),team=teamOf(pid),t=elapsed(),e={id:Date.now()+Math.random(),pid,type,t,phase:c.phase,team,void:false};if(type==='goal'){e.onTarget=true;if(team)c.score[team]++}if(type==='shot'){e.onTarget=false;e.pendingTarget=true}if(type==='save'){let opp=team==='A'?'B':'A',sh=[...c.events].reverse().find(x=>!x.void&&x.team===opp&&x.type==='shot'&&x.pendingTarget&&t-x.t>=0&&t-x.t<=SHOT_WINDOW);if(sh){sh.onTarget=true;sh.pendingTarget=false;sh.savedBy=pid;e.linkedShot=sh.id}}c.events.push(e);save();renderLive();toast(type==='goal'?'Gol: punteggio aggiornato':type==='save'&&e.linkedShot?'Parata collegata: tiro nello specchio':label(type))}
$$('[data-score]').forEach(b=>b.onclick=()=>{if(confirm('Correzione manuale del punteggio?')){C().score[b.dataset.score]++;save();renderLive()}});
function label(t){return({shot:'Tiro',goal:'Gol',assist:'Assist',save:'Parata',passok:'Pass +',passbad:'Pass -',lost:'Persa',recover:'Recupero'})[t]||t}
function updateTimer(){let s=elapsed();$('#timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');$('#phaseLabel').textContent=C().phase==='pausa'?'INTERVALLO':String(C().phase).toUpperCase()}
function snap(){let x={A:[],B:[]};for(let t of ['A','B'])x[t]=Object.values(C().teams[t]).map(v=>v?.pid).filter(Boolean).sort();return x}
function beginSeg(){if(C().activeSegment)return;let s=snap();C().activeSegment={start:elapsed(),scoreStart:{...C().score},A:s.A,B:s.B}}
function closeSeg(){let c=C();if(!c.activeSegment)return;c.segments.push({...c.activeSegment,end:elapsed(),scoreEnd:{...c.score}});c.activeSegment=null}
$('#playBtn').onclick=()=>{let c=C();if(c.startedAt)return;c.phase=c.phase==='ready'?'1° TEMPO':c.phase==='pausa'?'2° TEMPO':c.phase;c.startedAt=Date.now();beginSeg();save();clearInterval(tick);tick=setInterval(updateTimer,1000);updateTimer()};
$('#pauseBtn').onclick=()=>{let c=C();if(c.startedAt){c.elapsed=elapsed();c.startedAt=null}closeSeg();c.phase='pausa';clearInterval(tick);save();updateTimer()};
$('#stopBtn').onclick=()=>{let c=C();if(!c.id)return toast('Nessuna sessione attiva');if(c.startedAt){c.elapsed=elapsed();c.startedAt=null}closeSeg();c.phase='finita';clearInterval(tick);archive()};
function renderLast(){let e=[...C().events].reverse().find(x=>!x.void);$('#lastEvent').textContent=e?`· ${DB.roster.find(x=>x.id===e.pid)?.name||''} ${label(e.type)}`:''}
$('#undoBtn').onclick=()=>{let c=C(),e=[...c.events].reverse().find(x=>!x.void);if(!e)return toast('Niente da annullare');e.void=true;if(e.type==='goal'&&e.team&&c.score[e.team]>0)c.score[e.team]--;if(e.type==='save'&&e.linkedShot){let sh=c.events.find(x=>x.id===e.linkedShot);if(sh){sh.onTarget=false;sh.pendingTarget=true}}save();renderLive()};
$('#subBtn').onclick=()=>{let f=[...new Set(assigned())];$('#subChoices').innerHTML='<div class="sub">Chi esce?</div>'+f.map(id=>{let p=DB.roster.find(x=>x.id===id),a=assignmentOf(id);return`<button class="choice" data-out="${id}"><span><b>${esc(p?.name||'')}</b><small class="meta" style="display:block">Squadra ${a?.team} · ${a?.slot}</small></span>→</button>`}).join('');$$('[data-out]').forEach(b=>b.onclick=()=>chooseIn(b.dataset.out));$('#subModal').classList.add('show')};
function chooseIn(out){let c=C(),bench=DB.roster.filter(p=>c.present.includes(p.id)&&!assigned().includes(p.id)),a=assignmentOf(out),desired=a?.desired||'C',good=bench.filter(p=>compatible(p.role,desired)),other=bench.filter(p=>!compatible(p.role,desired));$('#subChoices').innerHTML=`<div class="sub">Chi entra al posto di ${esc(DB.roster.find(p=>p.id===out)?.name||'')}?</div><div class="groupTitle">CONSIGLIATI</div>`+good.map(p=>subChoice(p,out,desired,true)).join('')+'<div class="groupTitle">ADATTABILI</div>'+other.map(p=>subChoice(p,out,desired,false)).join('');$$('[data-in]').forEach(b=>b.onclick=()=>doSub(out,b.dataset.in,desired))}
function subChoice(p,out,d,ok){return`<button class="choice" data-in="${p.id}"><span><b>${esc(p.name)}</b><small class="meta" style="display:block">${RN[p.role]}</small></span><span class="tag ${ok?'':'warn'}">${ok?'di ruolo':'adattato'}</span></button>`}
function doSub(out,inn,desired){let c=C();if(c.startedAt){closeSeg()}for(let t of ['A','B'])for(let k in c.teams[t])if(c.teams[t][k]?.pid===out){let p=DB.roster.find(x=>x.id===inn);c.teams[t][k]={pid:inn,desired,outRole:!compatible(p.role,desired)};if(!compatible(p.role,desired))c.outRoles.push({pid:inn,team:t,slot:k,desired,at:elapsed()})}if(c.startedAt)beginSeg();save();$('#subModal').classList.remove('show');renderLive()}
function archive(){let c=C(),snap=JSON.parse(JSON.stringify(c));snap.scoreSystem='v1';DB.history.unshift(snap);DB.current=EC();save();renderHistory();go('storico');toast('Sessione salvata')}
function roleTop(rows,role,n){return rows.filter(x=>x.role===role).sort((a,b)=>b.vote-a.vote||b.points-a.points).slice(0,n)}
function sessionRows(s){let ids=[...new Set((s.present||[]).concat((s.events||[]).map(e=>e.pid)))];return ids.map(id=>{let p=DB.roster.find(x=>x.id===id),sc=playerScore(id,s);return{id,name:p?.name||'Giocatore',role:p?.role||'C',points:sc.total,vote:sc.vote,stats:pstats(id,s),out:(s.outRoles||[]).some(x=>x.pid===id)}})}
function bestSeven(rows){return [...roleTop(rows,'P',1),...roleTop(rows,'D',2),...roleTop(rows,'C',2),...roleTop(rows,'A',2)]}
function seasonRows(){let map={};for(const s of DB.history){for(const r of sessionRows(s)){let x=map[r.id]||(map[r.id]={id:r.id,name:r.name,role:r.role,sum:0,points:0,n:0});x.sum+=r.vote;x.points+=r.points;x.n++}}return Object.values(map).map(x=>({...x,vote:x.sum/x.n}))}
function renderHistory(){let h=$('#historyList');h.innerHTML=DB.history.length?DB.history.map((s,i)=>`<div class="historyItem"><div class="grow"><div class="name">${esc(s.title||'Allenamento')}</div><div class="meta">${esc(s.dateLabel||'')} · ${s.size}v${s.size} · ${s.score?.A??0}-${s.score?.B??0}</div></div><button class="btn small ghost" data-open="${i}">Apri</button><button class="btn small danger" data-hdel="${i}">Elimina</button></div>`).join(''):'<div class="empty">Nessuna sessione salvata.</div>';$$('[data-open]').forEach(b=>b.onclick=()=>openSession(+b.dataset.open));$$('[data-hdel]').forEach(b=>b.onclick=()=>{let i=+b.dataset.hdel;if(confirm('Eliminare definitivamente questa sessione?')){DB.history.splice(i,1);save();renderHistory()}});renderStats()}
function openSession(i){let s=DB.history[i],rows=sessionRows(s).sort((a,b)=>b.vote-a.vote||b.points-a.points),best=bestSeven(rows);$('#sessionDetail').innerHTML=`<div class="kpis"><div class="kpi"><b>${s.score?.A??0}-${s.score?.B??0}</b><small>Risultato</small></div><div class="kpi"><b>${s.size}v${s.size}</b><small>Formato</small></div><div class="kpi"><b>${Math.round((s.elapsed||0)/60)}</b><small>Minuti</small></div></div><h3>Valutazioni</h3>${rows.map(r=>`<div class="combo"><b>${esc(r.name)} · ${RN[r.role]} · voto ${r.vote.toFixed(1)}</b><span class="meta">${r.points.toFixed(1)} punti${r.out?' · ⚠️ fuori ruolo':''} · G ${r.stats.g} · A ${r.stats.a} · Tiri ${r.stats.sh} · Porta ${r.stats.on} · Pass ${r.stats.pp.toFixed(0)}%</span></div>`).join('')}<h3>Top 7 sessione</h3>${bestSevenHtml(best)}<h3>Fuori ruolo</h3>${(s.outRoles||[]).length?[...new Set((s.outRoles||[]).map(x=>x.pid))].map(id=>`<div class="combo">⚠️ ${esc(playerName(id))}</div>`).join(''):'<div class="sub">Nessuno.</div>'}`;$('#sessionModal').classList.add('show')}
function bestSevenHtml(rows){let labels={P:'POR',D:'DIF',C:'CEN',A:'ATT'};let wanted=[['P',1],['D',2],['C',2],['A',2]],html='';for(const [role,n] of wanted){let rr=rows.filter(x=>x.role===role);for(let i=0;i<n;i++){let r=rr[i];html+=r?`<div class="combo"><b>${labels[role]} · ${esc(r.name)} · ${r.vote.toFixed(1)}</b><span class="meta">${(r.points??0).toFixed(1)} punti${r.n?` · ${r.n} sessioni`:''}</span></div>`:`<div class="combo"><b>${labels[role]} · —</b><span class="meta">Nessun giocatore classificabile</span></div>`}}return html}
function renderStats(){let all=seasonRows(),seasonBest=[...roleTop(all,'P',1),...roleTop(all,'D',2),...roleTop(all,'C',2),...roleTop(all,'A',2)];let html='<h3>Migliori 7 per voto medio</h3><div class="sub">1 portiere · 2 difensori · 2 centrocampisti · 2 attaccanti</div>'+bestSevenHtml(seasonBest);for(const n of [3,4,5,6,7]){let ss=DB.history.filter(s=>s.size===n);html+=`<h3>${n} vs ${n}</h3>`+(ss.length?comboFor(ss):'<div class="sub">Nessun dato.</div>')}$('#comboAnalysis').innerHTML=html}
function comboFor(sessions){let map={};for(const s of sessions){for(const seg of s.segments||[]){let mins=Math.max(0,(seg.end-seg.start)/60);for(const t of ['A','B']){let ids=(seg[t]||[]).slice().sort(),opp=t==='A'?'B':'A',gf=(seg.scoreEnd?.[t]??0)-(seg.scoreStart?.[t]??0),ga=(seg.scoreEnd?.[opp]??0)-(seg.scoreStart?.[opp]??0);if(ids.length){let k=ids.join('|'),x=map[k]||(map[k]={ids,mins:0,gf:0,ga:0});x.mins+=mins;x.gf+=gf;x.ga+=ga}}}}let arr=Object.values(map).map(x=>({...x,diff:x.gf-x.ga})).sort((a,b)=>b.diff-a.diff||b.mins-a.mins).slice(0,5);return arr.length?arr.map(x=>`<div class="combo"><b>${x.ids.map(playerName).map(esc).join(' + ')}</b><span class="meta">${x.mins.toFixed(1)} min · GF ${x.gf} / GS ${x.ga} · diff ${x.diff>=0?'+':''}${x.diff}</span></div>`).join(''):'<div class="sub">Dati insufficienti.</div>'}
function playerName(id){return DB.roster.find(p=>p.id===id)?.name||'Giocatore'}
renderRoster();renderPresence();renderForm();renderLive();renderHistory();if(C().startedAt){clearInterval(tick);tick=setInterval(updateTimer,1000)}save();