const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const K='sevenlab06', PREV=['sevenlab05','sevenlab04','sevenlab03','sevenlab02','sevenlab01'], SHOT_WINDOW=8, LONG_PRESS=520;
const RN={P:'Portiere',D:'Difensore',C:'Centrocampista',A:'Attaccante'};
const F={
7:{'1-3-2-1':[['P','P',8,50],['D1','D',28,20],['D2','D',28,50],['D3','D',28,80],['C1','C',56,35],['C2','C',56,65],['A','A',82,50]],'1-3-3':[['P','P',8,50],['D1','D',28,20],['D2','D',28,50],['D3','D',28,80],['A1','A',70,20],['A2','A',70,50],['A3','A',70,80]],'1-2-3-1':[['P','P',8,50],['D1','D',29,34],['D2','D',29,66],['C1','C',56,18],['C2','C',56,50],['C3','C',56,82],['A','A',82,50]],'1-2-2-2':[['P','P',8,50],['D1','D',28,35],['D2','D',28,65],['C1','C',54,34],['C2','C',54,66],['A1','A',80,35],['A2','A',80,65]]},
6:{'1-2-1-2':[['P','P',8,50],['D1','D',29,34],['D2','D',29,66],['C','C',55,50],['A1','A',80,34],['A2','A',80,66]]},
5:{'2-2+J':[['DC1','D/C',27,30],['DC2','D/C',27,70],['J','C',50,50],['AC1','A/C',73,30],['AC2','A/C',73,70]]},
4:{'2-2':[['DC1','D/C',30,30],['DC2','D/C',30,70],['AC1','A/C',70,30],['AC2','A/C',70,70]]},
3:{'1-2':[['DC','D/C',30,50],['AC1','A/C',70,32],['AC2','A/C',70,68]]}
};
const FS=[['shot','🎯','Tiro'],['goal','⚽','Gol'],['dribble','🌀','Dribbling'],['passok','✓','Pass +'],['passbad','✕','Pass -'],['lost','❌','Persa'],['recover','🔄','Recupero']];
const KS=[['save','🧤','Parata'],['passok','✓','Pass +'],['passbad','✕','Pass -']];
const BASE={goal:5,assist:3,shot_on:1,shot_off:0,recover:1.5,lost:-1.5,passok:.2,passbad:-.5,save:2,dribble_ok:1.5,dribble_bad:-1};
const MULT={P:{save:1.35,passok:1.15,passbad:1.20},D:{goal:1,assist:1,shot_on:1,shot_off:1,recover:1.30,lost:1.20,passok:1.15,passbad:1.15},C:{goal:1.05,assist:1.20,shot_on:1.05,shot_off:1,recover:1.15,lost:1.10,passok:1.25,passbad:1.10},A:{goal:1.25,assist:1.10,shot_on:1.15,shot_off:1,recover:1,lost:1,passok:1,passbad:1}};
function EC(){return{id:null,dateISO:null,dateLabel:'',title:'',present:[],size:7,module:'1-2-3-1',teams:{A:{},B:{}},events:[],phase:'ready',elapsed:0,startedAt:null,score:{A:0,B:0},outRoles:[],segments:[],activeSegment:null}}
function load(){let d=JSON.parse(localStorage.getItem(K)||'null'); if(!d){for(const k of PREV){d=JSON.parse(localStorage.getItem(k)||'null');if(d)break}} d=d||{roster:[],history:[],current:EC()}; d.current=Object.assign(EC(),d.current||{}); d.roster=d.roster||[]; d.history=d.history||[]; return d}
let DB=load(),pick,tick,pendingGoal=null,pressTimers={};
function save(){localStorage.setItem(K,JSON.stringify(DB))} function C(){return DB.current}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(x){let e=$('#toast');e.textContent=x;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),950)}
function nd(){let d=new Date;return{iso:d.toISOString(),label:d.toLocaleDateString('it-IT',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})}}
function go(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));if(id==='formazioni')renderForm();if(id==='live')renderLive();if(id==='storico')renderHistory();scrollTo(0,0)}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go)); $$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.remove('show'));
$('#addBtn').onclick=()=>{let n=$('#newName').value.trim(),r=$('#newRole').value;if(!n)return toast('Inserisci un nome');DB.roster.push({id:''+Date.now()+Math.random(),name:n,role:r});$('#newName').value='';save();renderRoster();renderPresence()};
function renderRoster(){let e=$('#rosterList');e.innerHTML=DB.roster.length?DB.roster.map(p=>`<div class="player"><div class="avatar">${esc((p.name[0]||'?').toUpperCase())}</div><div class="grow"><div class="name">${esc(p.name)}</div><div class="meta">${RN[p.role]}</div></div><span class="role">${p.role}</span><button class="btn small danger" data-del="${p.id}">×</button></div>`).join(''):'<div class="empty">Aggiungi il primo giocatore.</div>';$$('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Rimuovere questo giocatore?')){DB.roster=DB.roster.filter(p=>p.id!==b.dataset.del);save();renderRoster();renderPresence()}})}
function renderPresence(){let d=nd();$('#todayLabel').textContent='Data automatica: '+d.label;let sel=C().present||[];$('#presenceList').innerHTML=DB.roster.length?DB.roster.map(p=>`<label><input type="checkbox" value="${p.id}" ${sel.includes(p.id)?'checked':''}><span>${esc(p.name)}<small class="meta" style="display:block">${p.role}</small></span></label>`).join(''):'<div class="empty">Prima inserisci la rosa.</div>'}
$('#presenceBtn').onclick=()=>{let d=nd(),ids=$$('#presenceList input:checked').map(x=>x.value);DB.current=EC();Object.assign(C(),{id:'s'+Date.now(),dateISO:d.iso,dateLabel:d.label,title:$('#trainingTitle').value.trim()||'Allenamento',present:ids});save();go('formazioni')};
function renderForm(){let c=C(),mods=Object.keys(F[c.size]);if(!mods.includes(c.module))c.module=mods[0];$('#sizeSeg').innerHTML=[3,4,5,6,7].map(n=>`<button class="seg ${c.size===n?'on':''}" data-size="${n}">${n} vs ${n}</button>`).join('');$('#moduleSeg').innerHTML=mods.map(m=>`<button class="seg ${c.module===m?'on':''}" data-mod="${m}">${m}</button>`).join('');$$('[data-size]').forEach(b=>b.onclick=()=>{c.size=+b.dataset.size;c.module=Object.keys(F[c.size])[0];c.teams={A:{},B:{}};save();renderForm()});$$('[data-mod]').forEach(b=>b.onclick=()=>{c.module=b.dataset.mod;c.teams={A:{},B:{}};save();renderForm()});renderPitch('A');renderPitch('B')}
function renderPitch(t){let c=C(),e=$('#pitch'+t);e.innerHTML='';F[c.size][c.module].forEach(([k,r,x,y])=>{let a=c.teams[t][k],p=DB.roster.find(z=>z.id===a?.pid),b=document.createElement('button');b.className='slot '+(!p?'empty':a.outRole?'outrole':'');b.style.left=x+'%';b.style.top=y+'%';b.innerHTML=p?`${esc(p.name)}<span class="tiny">${k}${a.outRole?' · fuori ruolo':''}</span>`:`+ ${k}<span class="tiny">${r}</span>`;b.onclick=()=>openPicker(t,k,r);e.appendChild(b)})}
function assigned(s=C()){return Object.values(s.teams.A||{}).concat(Object.values(s.teams.B||{})).map(x=>x?.pid).filter(Boolean)}
function compatible(r,d){return d==='D/C'?['D','C'].includes(r):d==='A/C'?['A','C'].includes(r):r===d}
function openPicker(t,k,d){pick={t,k,d};let c=C(),av=DB.roster.filter(p=>c.present.includes(p.id)&&(!assigned().includes(p.id)||c.teams[t][k]?.pid===p.id)),good=av.filter(p=>compatible(p.role,d)),other=av.filter(p=>!compatible(p.role,d));$('#pickerTitle').textContent=`Squadra ${t} · ${k} (${d})`;$('#pickerChoices').innerHTML=(c.teams[t][k]?'<button class="choice" data-pid="">➖ Libera posizione</button>':'')+`<div class="groupTitle">CONSIGLIATI (${good.length})</div>`+good.map(p=>choice(p,true)).join('')+`<div class="groupTitle">ADATTABILI (${other.length})</div>`+other.map(p=>choice(p,false)).join('');$$('#pickerChoices [data-pid]').forEach(b=>b.onclick=()=>assignPick(b.dataset.pid));$('#pickerModal').classList.add('show')}
function choice(p,ok){return`<button class="choice" data-pid="${p.id}"><span><b>${esc(p.name)}</b><small class="meta" style="display:block">${RN[p.role]}</small></span><span class="tag ${ok?'':'warn'}">${ok?'di ruolo':'adattato'}</span></button>`}
function assignPick(pid){let c=C();if(!pid)delete c.teams[pick.t][pick.k];else{let p=DB.roster.find(x=>x.id===pid),out=!compatible(p.role,pick.d);c.teams[pick.t][pick.k]={pid,desired:pick.d,outRole:out};if(out)c.outRoles.push({pid,team:pick.t,slot:pick.k,desired:pick.d,at:elapsed()})}save();$('#pickerModal').classList.remove('show');renderForm()}
$$('[data-clear]').forEach(b=>b.onclick=()=>{C().teams[b.dataset.clear]={};save();renderForm()}); $('#toLive').onclick=()=>go('live');
function teamOf(id,s=C()){return Object.values(s.teams.A||{}).some(x=>x?.pid===id)?'A':Object.values(s.teams.B||{}).some(x=>x?.pid===id)?'B':null}
function assignmentOf(id){for(let t of ['A','B'])for(let k in C().teams[t])if(C().teams[t][k]?.pid===id)return{team:t,slot:k,...C().teams[t][k]};return null}
function cnt(id,t,s=C()){return(s.events||[]).filter(e=>!e.void&&e.pid===id&&e.type===t).length}
function shots(id,s=C()){return cnt(id,'shot',s)+cnt(id,'goal',s)}
function onTarget(id,s=C()){return(s.events||[]).filter(e=>!e.void&&e.pid===id&&(e.type==='goal'||(e.type==='shot'&&e.onTarget))).length}
function pstats(id,s=C()){let sh=shots(id,s),g=cnt(id,'goal',s),on=onTarget(id,s),a=cnt(id,'assist',s),po=cnt(id,'passok',s),pb=cnt(id,'passbad',s),r=cnt(id,'recover',s),l=cnt(id,'lost',s),sv=cnt(id,'save',s),dok=cnt(id,'dribble_ok',s),dbad=cnt(id,'dribble_bad',s);return{sh,g,on,a,po,pb,r,l,sv,dok,dbad,pp:po+pb?po/(po+pb)*100:0,cv:sh?g/sh*100:0,tp:sh?on/sh*100:0,dr:dok+dbad?dok/(dok+dbad)*100:0}}
function eventKey(e){if(e.type==='shot')return e.onTarget?'shot_on':'shot_off';return e.type}
function playerScore(id,s){let p=DB.roster.find(x=>x.id===id),role=p?.role||'C',parts={},total=0;(s.events||[]).filter(e=>!e.void&&e.pid===id).forEach(e=>{let k=eventKey(e),base=BASE[k]??0,m=(k==='dribble_ok'||k==='dribble_bad')?1:((MULT[role]&&MULT[role][k])??1),val=base*m;parts[k]=(parts[k]||0)+val;total+=val});return{total,parts,vote:voteFromPoints(total)}}
function voteFromPoints(x){if(x<=-5)return 4;if(x<=-1)return 4.5;if(x<=3)return 5;if(x<=6)return 5.5;if(x<=10)return 6;if(x<=14)return 6.5;if(x<=19)return 7;if(x<=24)return 7.5;if(x<=30)return 8;if(x<=37)return 8.5;if(x<=45)return 9;if(x<=55)return 9.5;return 10}
function renderLive(){let c=C();updateTimer();$('#scoreA').textContent=c.score.A;$('#scoreB').textContent=c.score.B;let ids=[...new Set(assigned())];$('#livePlayers').innerHTML=ids.map(id=>{let p=DB.roster.find(x=>x.id===id),a=assignmentOf(id),set=p?.role==='P'?KS:FS,z=pstats(id,c),sc=playerScore(id,c);return`<div class="liveplayer"><div class="liveplayer-top"><div><div class="name">${esc(p?.name||'')}</div><div class="meta">${RN[p?.role]||''} ${a?.outRole?'· ⚠️ fuori ruolo':''}</div></div><span class="role">Squadra ${a?.team||''}</span></div><div class="countergrid ${p?.role==='P'?'keepergrid':''}">${set.map(([t,i,l])=>`<button class="counter nozoom" data-ev="${id}|${t}"><b>${i} ${t==='shot'?z.sh:t==='dribble'?(z.dok+z.dbad):cnt(id,t)}</b><small>${l}</small></button>`).join('')}</div><div class="microstats">Punti ${sc.total.toFixed(1)} · Voto ${sc.vote.toFixed(1)}${p?.role!=='P'?` · Tiri ${z.sh} · Porta ${z.on} · Dribbling ${z.dok}/${z.dok+z.dbad} · Succ. ${z.dr.toFixed(0)}%`:''}</div></div>`}).join('')||'<div class="empty">Prima prepara le formazioni.</div>';$$('[data-ev]').forEach(b=>{let [id,t]=b.dataset.ev.split('|');if(t==='dribble')wireDribble(b,id);else b.onclick=()=>t==='goal'?openAssist(id):addEvent(id,t)});renderLast()}
function wireDribble(btn,pid){let fired=false;const start=ev=>{ev.preventDefault();fired=false;clearTimeout(pressTimers[pid]);pressTimers[pid]=setTimeout(()=>{fired=true;addSimple(pid,'dribble_bad');toast('Dribbling non riuscito');if(navigator.vibrate)navigator.vibrate(30)},LONG_PRESS)};const end=ev=>{ev.preventDefault();clearTimeout(pressTimers[pid]);pressTimers[pid]=null;if(!fired){addSimple(pid,'dribble_ok');toast('Dribbling riuscito')}};btn.onpointerdown=start;btn.onpointerup=end;btn.onpointercancel=()=>clearTimeout(pressTimers[pid]);btn.oncontextmenu=e=>e.preventDefault()}
function elapsed(){let c=C();return c.elapsed+(c.startedAt?Math.floor((Date.now()-c.startedAt)/1000):0)}
function addSimple(pid,type,extra={}){let c=C(),team=teamOf(pid),e={id:Date.now()+Math.random(),pid,type,t:elapsed(),phase:c.phase,team,void:false,...extra};c.events.push(e);save();renderLive()}
function addEvent(pid,type){let c=C(),team=teamOf(pid),t=elapsed(),e={id:Date.now()+Math.random(),pid,type,t,phase:c.phase,team,void:false};if(type==='shot'){e.onTarget=false;e.pendingTarget=true}if(type==='save'){let opp=team==='A'?'B':'A',sh=[...c.events].reverse().find(x=>!x.void&&x.team===opp&&x.type==='shot'&&x.pendingTarget&&t-x.t>=0&&t-x.t<=SHOT_WINDOW);if(sh){sh.onTarget=true;sh.pendingTarget=false;sh.savedBy=pid;e.linkedShot=sh.id}}c.events.push(e);save();renderLive();toast(type==='save'&&e.linkedShot?'Parata: tiro nello specchio':label(type))}
function openAssist(scorer){let c=C(),team=teamOf(scorer),mates=assigned().filter(id=>id!==scorer&&teamOf(id)===team&&DB.roster.find(p=>p.id===id)?.role!=='P');pendingGoal={scorer,team};$('#assistTitle').textContent='Chi ha fatto assist?';$('#assistChoices').innerHTML='<button class="choice" data-assist="">🚫 Nessun assist</button>'+mates.map(id=>`<button class="choice" data-assist="${id}"><b>${esc(DB.roster.find(p=>p.id===id)?.name||'')}</b><span>+ assist</span></button>`).join('');$$('[data-assist]').forEach(b=>b.onclick=()=>commitGoal(b.dataset.assist));$('#assistModal').classList.add('show')}
function commitGoal(aid){let c=C(),{scorer,team}=pendingGoal||{};if(!scorer)return;let t=elapsed(),gid=Date.now()+Math.random();c.events.push({id:gid,pid:scorer,type:'goal',t,phase:c.phase,team,onTarget:true,void:false,assistPid:aid||null});if(aid)c.events.push({id:gid+'.a',pid:aid,type:'assist',t,phase:c.phase,team,goalId:gid,void:false});c.score[team]++;pendingGoal=null;$('#assistModal').classList.remove('show');save();renderLive();toast(aid?'Gol + assist registrati':'Gol senza assist')}
function label(t){return({shot:'Tiro',goal:'Gol',assist:'Assist',save:'Parata',passok:'Pass +',passbad:'Pass -',lost:'Persa',recover:'Recupero',dribble_ok:'Dribbling riuscito',dribble_bad:'Dribbling fallito'})[t]||t}
$$('[data-score]').forEach(b=>b.onclick=()=>{if(confirm('Correzione manuale del punteggio?')){C().score[b.dataset.score]++;save();renderLive()}});
function updateTimer(){let s=elapsed();$('#timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');$('#phaseLabel').textContent=C().phase==='pausa'?'INTERVALLO':String(C().phase).toUpperCase()}
function snap(){let x={A:[],B:[]};for(let t of ['A','B'])x[t]=Object.values(C().teams[t]).map(v=>v?.pid).filter(Boolean).sort();return x}
function beginSegment(){if(C().activeSegment)return;let s=snap();C().activeSegment={start:elapsed(),scoreStart:{...C().score},A:s.A,B:s.B}}
function closeSegment(){let c=C();if(!c.activeSegment)return;c.segments.push({...c.activeSegment,end:elapsed(),scoreEnd:{...c.score}});c.activeSegment=null}
$('#playBtn').onclick=()=>{let c=C();if(c.startedAt)return;c.phase=c.phase==='ready'?'1° TEMPO':c.phase==='pausa'?'2° TEMPO':c.phase;c.startedAt=Date.now();beginSegment();save();clearInterval(tick);tick=setInterval(updateTimer,1000);updateTimer()};
$('#pauseBtn').onclick=()=>{let c=C();if(c.startedAt){c.elapsed=elapsed();c.startedAt=null}closeSegment();c.phase='pausa';clearInterval(tick);save();updateTimer()};
$('#stopBtn').onclick=()=>{let c=C();if(!c.id)return toast('Nessuna sessione attiva');if(c.startedAt){c.elapsed=elapsed();c.startedAt=null}closeSegment();c.phase='finita';clearInterval(tick);archiveSession()};
function renderLast(){let e=[...C().events].reverse().find(x=>!x.void);$('#lastEvent').textContent=e?`· ${DB.roster.find(x=>x.id===e.pid)?.name||''} ${label(e.type)}`:''}
$('#undoBtn').onclick=()=>{let c=C(),e=[...c.events].reverse().find(x=>!x.void);if(!e)return toast('Niente da annullare');e.void=true;if(e.type==='goal'&&e.team&&c.score[e.team]>0){c.score[e.team]--;let a=c.events.find(x=>x.goalId===e.id&&!x.void);if(a)a.void=true}if(e.type==='save'&&e.linkedShot){let sh=c.events.find(x=>x.id===e.linkedShot);if(sh){sh.onTarget=false;sh.pendingTarget=true}}save();renderLive()};
$('#subBtn').onclick=()=>openSub();
function openSub(){let f=[...new Set(assigned())];$('#subChoices').innerHTML='<div class="sub">Chi esce?</div>'+f.map(id=>{let p=DB.roster.find(x=>x.id===id),a=assignmentOf(id);return`<button class="choice" data-out="${id}"><span><b>${esc(p?.name||'')}</b><small class="meta" style="display:block">Squadra ${a?.team} · ${a?.slot}</small></span>→</button>`}).join('');$$('[data-out]').forEach(b=>b.onclick=()=>chooseIn(b.dataset.out));$('#subModal').classList.add('show')}
function chooseIn(out){let c=C(),bench=DB.roster.filter(p=>c.present.includes(p.id)&&!assigned().includes(p.id)),a=assignmentOf(out),desired=a?.desired||'C';if(!bench.length)return toast('Nessuno in panchina');let good=bench.filter(p=>compatible(p.role,desired)),other=bench.filter(p=>!compatible(p.role,desired));$('#subChoices').innerHTML=`<div class="sub">Esce <b>${esc(DB.roster.find(p=>p.id===out)?.name||'')}</b>. Chi entra?</div><div class="groupTitle">CONSIGLIATI</div>`+good.map(p=>`<button class="choice" data-in="${p.id}"><b>${esc(p.name)}</b><span class="tag">di ruolo</span></button>`).join('')+`<div class="groupTitle">ADATTABILI</div>`+other.map(p=>`<button class="choice" data-in="${p.id}"><b>${esc(p.name)}</b><span class="tag warn">adattato</span></button>`).join('');$$('[data-in]').forEach(b=>b.onclick=()=>doSub(out,b.dataset.in))}
function doSub(out,inn){let c=C();closeSegment();for(let t of ['A','B'])for(let k in c.teams[t])if(c.teams[t][k]?.pid===out){let p=DB.roster.find(x=>x.id===inn),desired=c.teams[t][k].desired;c.teams[t][k]={pid:inn,desired,outRole:!compatible(p.role,desired)};if(c.teams[t][k].outRole)c.outRoles.push({pid:inn,team:t,slot:k,desired,at:elapsed()})}if(c.startedAt)beginSegment();c.events.push({id:Date.now()+Math.random(),pid:inn,type:'sub',outPid:out,t:elapsed(),void:false});save();$('#subModal').classList.remove('show');renderLive()}
function archiveSession(){let c=C(),copy=JSON.parse(JSON.stringify(c));copy.archivedAt=new Date().toISOString();DB.history.unshift(copy);DB.current=EC();save();renderHistory();go('storico');toast('Sessione salvata')}
function renderHistory(){let h=$('#historyList');h.innerHTML=DB.history.length?DB.history.map((s,i)=>`<div class="historyItem"><div class="grow"><div class="name">${esc(s.dateLabel||s.title||'Sessione')}</div><div class="meta">${s.size} vs ${s.size} · ${s.score?.A||0}-${s.score?.B||0} · ${Math.floor((s.elapsed||0)/60)} min</div></div><button class="btn small ghost" data-open="${i}">Apri</button><button class="btn small danger" data-hdel="${i}">×</button></div>`).join(''):'<div class="empty">Nessuna sessione salvata.</div>';$$('[data-open]').forEach(b=>b.onclick=()=>openSession(+b.dataset.open));$$('[data-hdel]').forEach(b=>b.onclick=()=>{let i=+b.dataset.hdel;if(confirm('Eliminare definitivamente questa sessione?')){DB.history.splice(i,1);save();renderHistory()}});renderAnalytics()}
function sessionPlayers(s){return [...new Set((s.events||[]).filter(e=>!e.void&&e.pid).map(e=>e.pid).concat(s.present||[]))]}
function openSession(i){let s=DB.history[i],ids=sessionPlayers(s),rows=ids.map(id=>{let p=DB.roster.find(x=>x.id===id),z=pstats(id,s),sc=playerScore(id,s);return{p,z,sc,id}}).filter(x=>x.p).sort((a,b)=>b.sc.vote-a.sc.vote||b.sc.total-a.sc.total),assists=assistLinks(s);$('#sessionDetail').innerHTML=`<div class="kpis"><div class="kpi"><b>${s.score.A}-${s.score.B}</b><small>Risultato</small></div><div class="kpi"><b>${s.size}v${s.size}</b><small>Formato</small></div><div class="kpi"><b>${Math.floor((s.elapsed||0)/60)}'</b><small>Durata</small></div></div><div class="exportbar"><button class="btn primary" data-export="print">📄 Report/PDF</button><button class="btn ghost" data-export="csv">📊 CSV</button><button class="btn ghost" data-export="share">📤 Condividi</button></div><div style="overflow:auto"><table class="report"><thead><tr><th>Giocatore</th><th>Voto</th><th>Pt</th><th>G</th><th>A</th><th>T</th><th>Rec</th><th>Pers</th><th>Drib</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.p.name)}</td><td>${x.sc.vote.toFixed(1)}</td><td>${x.sc.total.toFixed(1)}</td><td>${x.z.g}</td><td>${x.z.a}</td><td>${x.z.sh}</td><td>${x.z.r}</td><td>${x.z.l}</td><td>${x.z.dok}/${x.z.dok+x.z.dbad}</td></tr>`).join('')}</tbody></table></div>${assists.length?`<div class="groupTitle">CONNESSIONI GOL / ASSIST</div>${assists.map(x=>`<div class="combo"><b>${esc(playerName(x.a))} → ${esc(playerName(x.g))}</b><span class="meta">${x.n} assist</span></div>`).join('')}`:''}`;$$('[data-export]').forEach(b=>b.onclick=()=>b.dataset.export==='csv'?exportCSV(s):b.dataset.export==='print'?printReport(s):shareSession(s));$('#sessionModal').classList.add('show')}
function assistLinks(s){let m={};(s.events||[]).filter(e=>!e.void&&e.type==='goal'&&e.assistPid).forEach(e=>{let k=e.assistPid+'|'+e.pid;m[k]=(m[k]||0)+1});return Object.entries(m).map(([k,n])=>{let[a,g]=k.split('|');return{a,g,n}}).sort((a,b)=>b.n-a.n)}
function playerName(id){return DB.roster.find(p=>p.id===id)?.name||'Giocatore'}
function pairStatsBySize(size){let map={};for(const s of DB.history.filter(x=>x.size===size)){for(const seg of s.segments||[]){let mins=Math.max(0,(seg.end-seg.start)/60);if(!mins)continue;for(const team of ['A','B']){let ids=(seg[team]||[]).slice().sort(),opp=team==='A'?'B':'A',gf=(seg.scoreEnd?.[team]||0)-(seg.scoreStart?.[team]||0),ga=(seg.scoreEnd?.[opp]||0)-(seg.scoreStart?.[opp]||0);for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){let k=ids[i]+'|'+ids[j],x=map[k]||(map[k]={ids:[ids[i],ids[j]],mins:0,gf:0,ga:0,sessions:new Set()});x.mins+=mins;x.gf+=gf;x.ga+=ga;x.sessions.add(s.id)}}}}}return Object.values(map).map(x=>({...x,diff:x.gf-x.ga,sessionCount:x.sessions.size})).filter(x=>x.mins>=15&&x.sessionCount>=2).sort((a,b)=>(b.diff/Math.max(b.mins,1))-(a.diff/Math.max(a.mins,1))).slice(0,5)}
function lineupStatsBySize(size){let map={};for(const s of DB.history.filter(x=>x.size===size)){for(const seg of s.segments||[]){let mins=Math.max(0,(seg.end-seg.start)/60);if(!mins)continue;for(const team of ['A','B']){let ids=(seg[team]||[]).slice().sort();if(ids.length!==size)continue;let opp=team==='A'?'B':'A',gf=(seg.scoreEnd?.[team]||0)-(seg.scoreStart?.[team]||0),ga=(seg.scoreEnd?.[opp]||0)-(seg.scoreStart?.[opp]||0),k=ids.join('|'),x=map[k]||(map[k]={ids,mins:0,gf:0,ga:0,sessions:new Set()});x.mins+=mins;x.gf+=gf;x.ga+=ga;x.sessions.add(s.id)}}}}return Object.values(map).map(x=>({...x,diff:x.gf-x.ga,sessionCount:x.sessions.size})).filter(x=>x.mins>=15&&x.sessionCount>=2).sort((a,b)=>(b.diff/Math.max(b.mins,1))-(a.diff/Math.max(a.mins,1))).slice(0,3)}
function topSeven(){let rec={};for(const s of DB.history){for(const id of sessionPlayers(s)){let p=DB.roster.find(x=>x.id===id);if(!p)continue;let sc=playerScore(id,s),x=rec[id]||(rec[id]={p,n:0,sum:0});x.n++;x.sum+=sc.vote}}let all=Object.values(rec).map(x=>({...x,avg:x.sum/x.n})),take=(r,n)=>all.filter(x=>x.p.role===r).sort((a,b)=>b.avg-a.avg).slice(0,n);return [...take('P',1),...take('D',2),...take('C',2),...take('A',2)]}
function renderAnalytics(){let e=$('#comboAnalysis'),top=topSeven(),html=`<div class="groupTitle">MIGLIOR 7 PER VOTO MEDIO</div>${top.length?top.map(x=>`<div class="combo"><b>${esc(x.p.name)} · ${RN[x.p.role]}</b><span class="meta">Media ${x.avg.toFixed(2)} · ${x.n} sessioni</span></div>`).join(''):'<div class="sub">Servono sessioni registrate.</div>'}`;for(const size of [3,4,5,6,7]){let pairs=pairStatsBySize(size),lines=lineupStatsBySize(size);html+=`<div class="groupTitle">${size} VS ${size}</div>`;if(!pairs.length&&!lines.length){html+='<div class="sub">Nessun dato affidabile: servono almeno 15 minuti e 2 sessioni con la stessa combinazione.</div>';continue}if(lines.length){html+='<div class="meta" style="margin:6px 0">Line-up migliori</div>'+lines.map(x=>comboHtml(x,'lineup')).join('')}if(pairs.length){html+='<div class="meta" style="margin:10px 0 6px">Coppie con intesa positiva</div>'+pairs.map(x=>comboHtml(x,'pair')).join('')}}e.innerHTML=html}
function comboHtml(x,type){let rate=x.diff/Math.max(x.mins,1)*30,cls=x.diff>=0?'positive':'negative';return`<div class="combo"><b>${x.ids.map(playerName).map(esc).join(type==='pair'?' + ':' · ')}</b><span class="meta">${x.mins.toFixed(1)} min · ${x.sessionCount} sessioni · GF ${x.gf} / GS ${x.ga} · <span class="${cls}">${x.diff>=0?'+':''}${x.diff}</span> · diff/30' ${rate>=0?'+':''}${rate.toFixed(1)}</span></div>`}
function exportCSV(s){let ids=sessionPlayers(s),head=['Giocatore','Ruolo','Voto','Punti','Gol','Assist','Tiri','Tiri in porta','Pass+','Pass-','Recuperi','Perse','Dribbling riusciti','Dribbling falliti','Parate'],rows=ids.map(id=>{let p=DB.roster.find(x=>x.id===id),z=pstats(id,s),sc=playerScore(id,s);return[p?.name||'',RN[p?.role]||'',sc.vote.toFixed(1),sc.total.toFixed(1),z.g,z.a,z.sh,z.on,z.po,z.pb,z.r,z.l,z.dok,z.dbad,z.sv]});let csv=[head,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');downloadBlob(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),`SevenLab_${safeName(s.dateLabel||s.title)}_${s.size}v${s.size}.csv`)}
function safeName(x){return String(x||'sessione').replace(/[^\w\-]+/g,'_')}
function downloadBlob(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function printReport(s){let ids=sessionPlayers(s).map(id=>({id,p:DB.roster.find(x=>x.id===id),z:pstats(id,s),sc:playerScore(id,s)})).filter(x=>x.p).sort((a,b)=>b.sc.vote-a.sc.vote),w=window.open('','_blank');if(!w)return toast('Consenti i popup per creare il report');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>SevenLab Report</title><style>body{font-family:-apple-system,Arial;padding:24px;color:#111}h1{margin:0}small{color:#666}table{width:100%;border-collapse:collapse;margin-top:20px;font-size:12px}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:right}th:first-child,td:first-child{text-align:left}.head{display:flex;justify-content:space-between}.score{font-size:32px;font-weight:800}.note{margin-top:18px;padding:12px;background:#f3f5f3;border-radius:10px}@media print{button{display:none}}</style></head><body><div class="head"><div><h1>⚽ SevenLab</h1><small>${esc(s.dateLabel||'')} · ${s.size}v${s.size} · ${esc(s.module||'')}</small></div><div class="score">${s.score.A}-${s.score.B}</div></div><table><thead><tr><th>Giocatore</th><th>Ruolo</th><th>Voto</th><th>Pt</th><th>G</th><th>A</th><th>T</th><th>Rec</th><th>Pers</th></tr></thead><tbody>${ids.map(x=>`<tr><td>${esc(x.p.name)}</td><td>${RN[x.p.role]}</td><td>${x.sc.vote.toFixed(1)}</td><td>${x.sc.total.toFixed(1)}</td><td>${x.z.g}</td><td>${x.z.a}</td><td>${x.z.sh}</td><td>${x.z.r}</td><td>${x.z.l}</td></tr>`).join('')}</tbody></table><div class="note">Da iPhone: nella schermata Stampa usa Condividi per salvare o inviare il PDF.</div><script>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close()}
async function shareSession(s){let top=sessionPlayers(s).map(id=>({id,v:playerScore(id,s).vote})).sort((a,b)=>b.v-a.v)[0],txt=`SevenLab · ${s.dateLabel||s.title}\n${s.size}v${s.size} · ${s.score.A}-${s.score.B}${top?`\nMVP: ${playerName(top.id)} (${top.v.toFixed(1)})`:''}`;if(navigator.share){try{await navigator.share({title:'SevenLab',text:txt});return}catch(e){}}navigator.clipboard?.writeText(txt);toast('Riepilogo copiato')}
function exportBackup(){downloadBlob(new Blob([JSON.stringify(DB,null,2)],{type:'application/json'}),`SevenLab_backup_${new Date().toISOString().slice(0,10)}.json`)}
$('#backupBtn').onclick=exportBackup;
document.addEventListener('dblclick',e=>{if(e.target.closest('.nozoom'))e.preventDefault()},{passive:false});
renderRoster();renderPresence();renderForm();renderLive();renderHistory();if(C().startedAt){clearInterval(tick);tick=setInterval(updateTimer,1000)}save();